easy_admin:
    entities:
        Photo:
            class: App\Entity\Photo
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'external id', type: 'string', label: 'Zewnętrzne ID'}
                    - { property: 'Title', type: 'string', label: 'Tytuł'}
                    - { property: 'Pub date', type: 'datetime', label: 'Data Publikacji'}
                    - { property: 'Insert date', type: 'datetime', label: 'Data dodania'}
                    - { property: 'photo.path', type: 'image', base_path: '/photos/', label: 'Zdjęcie'}
            form:
                fields:
                    - { property: 'photo', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Photo' }, base_path: '/photos/', label: 'Zdjęcie'}
#        - App\Entity\Article
#        - App\Entity\Photo
#        - App\Entity\User
